### ISSUE TITLE
Image URL

### ISSUE THREAD

**Issue by nwittwer** [louisondumont/facematch#1]
I think I have everything set up, but it seems like the image URLs aren't working as after running the server and doing the POST request, I get an error about it being "undefined: 1" [Not Found] and a link back to Facebook. Wondering if I should be putting in the URL to an existing Facebook image or if I can use a local image and it will recognize it (or if this isn't the main problem). Any help or suggestions would be appreciated!

Full error message:

```
undefined:1
Not Found <br /><a href="http://www.facebook.com/">Back to Facebook.</a>
^

SyntaxError: Unexpected token N
    at Object.parse (native)
    at Request.cb [as _callback] (/Users/Nick/Desktop/facematch/lib/recognize.js:32:23)
    at Request.self.callback (/Users/Nick/Desktop/facematch/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/Nick/Desktop/facematch/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/Nick/Desktop/facematch/node_modules/request/request.js:962:12)
    at emitNone (events.js:72:20)
```

**Comment by louisondumont** [comment]
I don't think the problem is the image URL. You can post any publicly available (= accessible to Facebook' servers) image URL (so local urls won't work, upload it somewhere before posting).

Make sure that:
- the access token in the request is alive
- the cookies in config.js are correct
- the req params in config.js are correct
