### ISSUE TITLE
undefined:1 exiting server

### ISSUE THREAD

**Issue by daweedco** [louisondumont/facematch#5]
Hi,

I love the idea, but I can't get it to work.. I did everything step with no problem but when i'm trying to POST a request, i get this message in my terminal : 

undefined:1
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request.cb [as _callback](/Users/david/facematch/lib/recognize.js:32:23)
    at Request.self.callback (/Users/david/facematch/node_modules/request/request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/Users/david/facematch/node_modules/request/request.js:1036:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/Users/david/facematch/node_modules/request/request.js:963:12)
    at emitNone (events.js:85:20)

And I get no response header from POST request with status 0!

Thanks !

**Comment by louisondumont** [comment]
Yes the code still has poor error handling, this is a hack and I didn't take the time to set things up properly. That can mean two things:
- You didn't properly insert your values in config.js
- The image you're trying to recognize can't be fetched by Facebook (is it publicly accessible?)
